config/routes.rb
Rails.application.routes.draw do
  root 'home#show'

  resources :branches, only: :show
  resources :reviews, only: :show
  resources :assessment_forms, only: %i[new create]
  resources :prefectures, only: :show
  resources :cities, only: :show
  resources :thanks, only: :index

  namespace :api do
    resources :prefectures, only: :show
  end
end

app/models/branch.rb
class Branch < ApplicationRecord
  belongs_to :company
  belongs_to :city
  has_many :available_areas, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :cities, through: :available_areas

  validates :ieul_branch_id, uniqueness: true
  validates :name, uniqueness: { scope: %i[company_id ieul_branch_id] }

  # 平均評価の算出
  def average_satisfaction_level
    total_rating = 0

    reviews.each do |review|
      total_rating += review[:satisfaction_level]
    end

    result = (Float(total_rating) / reviews.length).round(1)

    result.nan? ? 0 : result
  end
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  def show
    @branch = Branch.find(params[:id])
    @branch_reviews = @branch.reviews.order(sold_at: 'DESC')
  end
end

app/helpers/branches_helper.rb
module BranchesHelper
  # 価格をフォーマットする
  # 例）20000000 => 2,000万円
  def format_price(price)
    price /= 10000

    # FIXME: price.to_s(:delimited)を使いたかったが動かなかった
    "#{price.to_s.gsub(/(\d)(?=\d{3}+$)/, '\\1,')}万円"
  end

  # 日付をフォーマットする
  # 例）2022-09-12 => 2022年9月
  def format_date(date)
    date.strftime("%Y年%-m月")
  end
end

app/views/branches/_company_info.html.erb
<div class="d-sm-flex d-block gap-5" style="margin-bottom: 10rem">
  <div>
    <p class="fw-bold mb-3"><%= branch.company.name %>について</p>
    <p class="mb-0">企業名 : <%= branch.company.name %></p>
    <p class="mb-0">郵便番号 : <%= branch.zip_code %></p>
    <p class="mb-0">住所 : <%= branch.city.prefecture.name %><%= branch.city.name %><%= branch.after_address %></p>
    <p class="mb-0">電話番号 : <%= branch.phone_number %></p>
    <p class="mb-0">FAX : <%= branch.fax_number %></p>
    <p class="mb-0">営業時間 : <%= branch.business_hours %></p>
    <p class="mb-0">定休日 : <%= branch.closed_day %></p>
  </div>
  <div class="d-flex align-items-center mt-3 mt-sm-0">
    <%= image_tag branch.company.logo_url, :alt => 'company_logo', width: 150 %>
  </div>
</div>

app/views/branches/_review.html.erb
<%= link_to(review, class: 'text-decoration-none text-body') do %>
  <div class="card mb-2">
    <div class="card-body">
      <p class="fw-bold"><%= review.name %>：★<%= review.satisfaction_level %></p>
      <p><%= review.comment_reason_for_satisfaction %></p>
      <div>
        <p>成約価格<%= format_price(review.contract_price) %></p>
        <p>(<%= review.city.prefecture.name %><%= review.city.name %> <%= format_date(review.sold_at) %>に売却)</p>
      </div>
    </div>
  </div>
<% end %>

app/views/branches/show.html.erb
<h1 class="text-center mb-5">
  <%= @branch.company.name %><%= @branch.name %>
</h1>

<div class='mb-3'>
  <%= link_to 'Home', root_path , class: 'inline text-decoration-none text-secondary' %>
  <span class='px-3'>></span>
  <%= link_to "#{@branch.city.prefecture.name}", prefecture_path(@branch.city.prefecture) , class: 'inline text-decoration-none text-secondary' %>
  <span class='px-3'>></span>
  <%= link_to "#{@branch.city.name}", @branch.city, class: 'inline text-decoration-none text-secondary' %>
  <span class='px-3'>></span>
  <% if @branch.name %>
    <span><%= @branch.name %></span>
  <% else %>
    <span><%= @branch.company.name %></span>
  <% end %>
</div>

<div class="mb-5">
  <h3><%= @branch.company.catch_copy %></h3>
  <p><%= @branch.introduction %></p>
</div>

<div class="mb-5">

  <p class="fw-bold"><%= @branch.company.name %>についての口コミ<% unless @branch_reviews.blank? %>(平均評価 ★<%= @branch.average_satisfaction_level %>)<% end %></p>
  <% if @branch_reviews.blank? %>
    <p>口コミがありません</p>
  <% else %>
    <%= render partial: 'review', collection: @branch_reviews, as: :review %>
  <% end %>
</div>

<%= render 'company_info', branch: @branch %>

<%= render "layouts/to_assessment_form_button", ieul_branch_id: @branch.ieul_branch_id %>