config/routes.rb
Rails.application.routes.draw do
  root 'home#show'

  resources :branches, only: :show
  resources :reviews, only: :show
  resources :assessment_forms, only: %i[new create]
  resources :prefectures, only: :show
  resources :cities, only: :show
  resources :thanks, only: :index

  namespace :api do
    resources :prefectures, only: :show
  end
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
  has_many :cities, dependent: :restrict_with_exception

  validates :name, uniqueness: true
end

app/controllers/api/prefectures_controller.rb
module Api
  class PrefecturesController < ApplicationController
    def show
      prefecture = Prefecture.find(params[:id])
      render json: prefecture.cities
    end
  end
end

app/controllers/prefectures_controller.rb
class PrefecturesController < ApplicationController
  def show
    @prefecture = Prefecture.find(params[:id])

    branch_ids = AvailableArea.where(city_id: @prefecture.cities.ids).pluck(:branch_id)

    # HACK: 店舗が増えると処理も重くなるため、ゆくゆくは定期実行->カラム更新などで対応したい
    @prefecture_branches = Branch.where(id: branch_ids).eager_load(:reviews, :company, city: [:prefecture]).sort do
      |a, b| b.average_satisfaction_level <=> a.average_satisfaction_level
    end
  end
end

app/views/prefectures/show.html.erb
<h1 class="text-center mb-5"><%= @prefecture.name %>の不動産会社</h1>

<div class='mb-3'>
  <%= link_to 'Home', root_path , class: 'inline text-decoration-none text-secondary' %>
  <span class='px-3'>></span>
  <span><%= @prefecture.name %></span>
</div>

<div class="mb-5">
  <h2><%= @prefecture.name %>全域</h2>
  <% if @prefecture.cities.blank? %>
    <p>査定可能な不動産会社がありません</p>
  <% else %>
    <section class="accordion">
      <input id="block-01" type="checkbox" class="toggle">
      <label class="Label" for="block-01" style="cursor: pointer">市区町村を選択</label>
      <div class="content">
        <ul class="list-group list-group-flush">
          <% @prefecture.cities.each do |city| %>
            <%= link_to(city_path(city), class: 'text-decoration-none text-body') do %>
              <li class="list-group-item"><%= city.name %></li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </section>
  <% end %>
</div>

<div class="mb-5">
  <%= render partial: 'layouts/branch_info', collection: @prefecture_branches, as: :branch %>
</div>

<style>
  /*ベース*/
.toggle {
  display: none;
}
.Label {		/*タイトル*/
  padding: 1em;
  display: block;
  color: #fff;
  background:#0d6efd;
}
.Label::before{		/*タイトル横の矢印*/
  content:"";
  width: 6px;
  height: 6px;
  border-top: 2px solid #fff;
  border-right: 2px solid #fff;
  -webkit-transform: rotate(45deg);
  position: absolute;
  top:calc( 50% - 3px );
  right: 20px;
  transform: rotate(135deg);
}
.Label,
.content {
  -webkit-backface-visibility: hidden;
  backface-visibility: hidden;
  transform: translateZ(0);
  transition: all 0.3s;
}
.content {		/*本文*/
  height: 0;
  margin-bottom:10px;
  padding:0 20px;
  overflow: hidden;
}
.toggle:checked + .Label + .content {	/*開閉時*/
  height: auto;
  padding:20px ;
  transition: all .3s;
}
.toggle:checked + .Label::before {
  transform: rotate(-45deg) !important;
}
</style>