config/routes.rb
Rails.application.routes.draw do
  root 'home#show'

  resources :branches, only: :show
  resources :reviews, only: :show
  resources :assessment_forms, only: %i[new create]
  resources :prefectures, only: :show
  resources :cities, only: :show
  resources :thanks, only: :index

  namespace :api do
    resources :prefectures, only: :show
  end
end

app/views/layouts/_branch_info.html.erb
  <%= link_to(branch, class: 'text-decoration-none text-body') do %>
    <div class="card mb-2">
      <div class="card-body">
        <div class="row">
          <div class="col">
            <p><%= branch.company.name %><%= branch.name %></p>
          </div>
          <div class="col-9">
            <p><%= branch.business_hours %></p>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <p>★<%= branch.average_satisfaction_level %></p>
          </div>
          <div class="col-9">
            <p><%= branch.closed_day %></p>
          </div>
        </div>
        <div class="row">
          <div class="col"></div>
          <div class="col-9">
            <p>住所：<%= branch.city.prefecture.name %><%= branch.city.name %><%= branch.after_address %></p>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <p>決め手：</p>
          </div>
          <div class="col-9">
            <% if branch.reviews.blank? %>
              <p>口コミがありません</p>
            <% else %>
              <p><%= branch.reviews.first.comment_reason_to_decide %></p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>

app/views/layouts/_to_assessment_form_button.html.erb
<div class="fixed-bottom bg-white text-center p-4">
  <%= link_to "査定依頼をする", new_assessment_form_path(ieul_branch_id: ieul_branch_id), class: 'btn btn-secondary py-2 px-5' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="bg-light">
  <head>
    <title>HrEngInternship20222ndTeam1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>

  <body class="bg-light">
    <div class="d-flex">
      <%= link_to root_path do %>
        <%= image_tag 'logo.png',size: '80x70' %>
        <h2 class="mt-3">
          <%= link_to("おうち査定ナビ", root_path, class:"text-decoration-none text-body fw-bold header") %>
        </h2>
      <% end %>

    </div>
    <div class="container">
      <%= yield %>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
      <script src="https://code.jquery.com/jquery-3.6.1.slim.js" integrity="sha256-tXm+sa1uzsbFnbXt8GJqsgi2Tw+m4BLGDof6eUPjbtk=" crossorigin="anonymous"></script>
    </div>
  </body>
</html>